apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: today-sherondale-me-tls
spec:
  secretName: today-sherondale-me
  issuerRef:
    name: letsencrypt-today
    kind: ClusterIssuer
  commonName: today.sherondale.me
  dnsNames:
    - today.sherondale.me
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - today.sherondale.me
