apiVersion: v1
kind: Service
metadata:
  name: multi-docker-client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: multi-docker-client
  ports:
    - port: 3000
      targetPort: 3000
