apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - sherondale.me
        - www.sherondale.me
      secretName: sherondale-me
  rules:
    - host: sherondale.me
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: multi-docker-client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: multi-docker-server-cluster-ip-service
              servicePort: 5000
    - host: www.sherondale.me
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: multi-docker-client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: multi-docker-server-cluster-ip-service
              servicePort: 5000
